<?php

namespace App\Models;

use Illuminate\Support\Str;
use Laratrust\Models\LaratrustPermission;

class Permission extends LaratrustPermission
{
    public $guarded = [];


    protected static function boot()
    {
        parent::boot(); // TODO: Change the autogenerated stub
        self::saving(function ($raw) {
            $name = $raw->name;
            $raw->name = Str::replace(' ', '_', Str::lower($name));
            $raw->display_name = Str::replace('_', ' ', Str::lower($name));
            $raw->description = Str::replace('_', ' ', ucwords($name));
        });


    }
}
